browser: Google Chrome.app
allocation:
  index: "REF case study identifier"
  type: excel
  sheet: Impact case studies
  filename: 2021-10-09-NLawrence-UOA11-Personal.xlsx
  directory: $HOME/Documents/ref
  converters:
  - field: Comment 1
    type: str_type
  - field: Comment 2
    type: str_type
  - field: Comment 3
    type: str_type
  - field: Comment 4
    type: str_type
  - field: Comment 5
    type: str_type
  header: 3

additional:
  index: "REF case study identifier"
  type: excel
  sheet: Additional case study data
  filename: 2021-10-09-NLawrence-UOA11-Personal.xlsx
  directory: $HOME/Documents/ref
  converters: {}
  header: 2

scores:
  index: "REF case study identifier"
  type: excel
  sheet: Impact case studies
  directory: $HOME/Documents/ref
  filename: upload_this_version_impact.xlsx
  converters:
  - field: Comment 1
    type: str_type
  - field: Comment 2
    type: str_type
  - field: Comment 3
    type: str_type
  - field: Comment 4
    type: str_type
  - field: Comment 5
    type: str_type
  header: 3

viewer:
- display: "### {title}
"
  format:
    title: Case study title

urls:
- display:
    url: https://www.semanticscholar.org/search?q=
    field: Case study title

localpdf:
- display:
    directory: $HOME/Documents/ref
    field: LocalDocumentLink

scored:
  field: "Significance Score"

scorer:
- field: "Significance Score"
  type: IntSlider
  args:
    value: 2
    min: 0
    max: 4
    step: 1
    description: "Significance Score"
- field: "Significance Comment"
  type: Text
  args:
    value: "S:"
    description: "Significance Comment"
- field: "Reach Score"
  type: IntSlider
  args:
    value: 2
    min: 0
    max: 4
    step: 1
    description: "Reach Score"
- field: "Reach Comment"
  type: Text
  args:
    value: "R:"
    description: "Reach Comment"
  timestamp_field: "Comment 5"
    
