datadirectory: $HOME/Documents/ref
allocation: 2021-10-09-NLawrence-UOA11-Personal.xlsx
upload: upload_this_version.xlsx
outputs_sheet: Outputs
additional_data_sheet: Additional output data
case_study_sheet: Impact case studies
additional_case_study_data_sheet: Additional case study data
environment_sheet: Environment
aberysthwyth_threshold: 367130
