browser: Google Chrome.app
allocation:
  index: REF Submission Id
  type: excel
  sheet: Environment
  filename: 2021-11-30-NLawrence-UOA11-Personal.xlsx
  directory: $HOME/Documents/ref
  converters:
  - field: Comments
    type: str_type
  - field: Comments.1
    type: str_type
  - field: Comments.2
    type: str_type
  - field: Comments.3
    type: str_type
  - field: Comment 2
    type: str_type
  - field: Comment 3
    type: str_type
  header: 4


scores:
  index: REF Submission Id
  type: excel
  sheet: Environment
  directory: $HOME/Documents/ref
  filename: upload_this_version_environment.xlsx
  converters:
  - field: Strategy.1
    type: str_type
  - field: Comments
    type: str_type
  - field: Comments.1
    type: str_type
  - field: Comments.2
    type: str_type
  - field: Comments.3
    type: str_type
  - field: Comment 2
    type: str_type
  - field: Comment 3
    type: str_type
  header: 0

viewer:
- display: "### {submissionid}
"
  format:
    submissionid: REF Submission Id

localpdf:
- directory: $HOME/Documents/ref
  field: LocalDocumentLink

scored:
  field: "Strategy Score"

scorer:
- field: "Strategy0"
  type: Label
  args:
    value: "Stategy Score"
- field: "Strategy Score"
  type: IntSlider
  args:
    value: 4
    min: 0
    max: 8
    step: 1
    description: "Strategy"
- field: "Strategy1"
  type: Label
  args:
    value: How research is structured across the submitted unit, to provide context for assessment.
- field: "Structure"
  type: Text
  args:
    value: ""
    description: "Structure"
- field: "Strategy2"
  type: Label
  args:
    value: Research objectives for the period (including review of REF 2014 plans) and next five years.
- field: "Strategy.1"
  type: Text
  args:
    value: ""
    description: "Strategy"
- field: "Strategy3"
  type: Label
  args:
    value: Current and future approach to achieving impact and how this is exemplified by submitted case studies.
- field: "Impact"
  type: Text
  args:
    value: ""
    description: "Impact"
- field: "Strategy4"
  type: Label
  args:
    value: Approach to supporting interdisciplinary research (only) if this has enhanced vitality and sustainability.
- field: "Interdisciplinarity"
  type: Text
  args:
    value: ""
    description: "Interdisciplinarity"
- field: "Strategy5"
  type: Label
  args:
    value: Progress towards an open and reproducible research environment beyond REF open access requirements.
- field: "Open Research"
  type: Text
  args:
    value: ""
    description: "Open Research"
- field: Strategy6
  type: Label
  args:
    value: Support for a culture of research integrity, including ethical, legal and professional standards. Section 2. 
- field: "Research Integrity"
  type: Text
  args:
    value: ""
    description: "Research Integrity"
- field: "Strategy Overall"
  type: Text
  args:
    value: ""
    description: "Strategy Overall"
- field: "People Score"
  type: IntSlider
  args:
    value: 4
    min: 0
    max: 8
    step: 1
    description: "People"
- field: "Income Score"
  type: IntSlider
  args:
    value: 4
    min: 0
    max: 8
    step: 1
    description: "Income"
- field: "Collaboration Score"
  type: IntSlider
  args:
    value: 4
    min: 0
    max: 8
    step: 1
    description: "Collaboration"
    
timestamp_field: "Timestamp"
    
